apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isbehandlerdialog
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isbehandlerdialog.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
        - application: padm2
    outbound:
      external:
        - host: "dokarkiv.prod-fss-pub.nais.io"
      rules:
        - application: dialogmeldingpdfgen
        - application: padm2
        - application: isoppfolgingstilfelle
        - application: istilgangskontroll
        - application: pale-2-pdfgen
          namespace: teamsykmelding
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: isbehandlerdialog-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KTOR_ENV
      value: "production"
    - name: LEGEERKLARING_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-prod
    - name: LEGEERKLARING_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-prod
    - name: PADM2_CLIENT_ID
      value: "prod-gcp.teamsykefravr.padm2"
    - name: PADM2_URL
      value: "http://padm2"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: DOKARKIV_CLIENT_ID
      value: "prod-fss.teamdokumenthandtering.dokarkiv"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: "http://isoppfolgingstilfelle"
    - name: CRONJOB_UBESVART_MELDING_INTERVAL_DELAY_MINUTES
      value: "240" # Hver fjerde time, 60*4
    - name: CRONJOB_UBESVART_MELDING_FRIST_HOURS
      value: "504" # Etter tre uker, 21*24
    - name: CRONJOB_AVVIST_MELDING_STATUS_INTERVAL_DELAY_MINUTES
      value: "240" # Hver fjerde time, 60*4
