CREATE TABLE MELDING_STATUS
(
    id         SERIAL PRIMARY KEY,
    melding_id INTEGER REFERENCES melding (id) ON DELETE CASCADE,
    uuid       VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    status     VARCHAR(10) NOT NULL,
    tekst      VARCHAR(100)
);

CREATE INDEX IX_MELDING_STATUS_MELDING_ID ON MELDING_STATUS (melding_id);
