package no.nav.syfo.melding.domain

enum class MeldingType {
    FORESPORSEL_PASIENT_TILLEGGSOPPLYSNINGER,
    FORESPORSEL_PASIENT_LEGEERKLARING,
    FORESPORSEL_PASIENT_PAMINNELSE,
    HENVENDELSE_RETUR_LEGEERKLARING,
}
